version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: es
    environment:
      - node.name=es
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
        #  kibana:
        #    image: docker.elastic.co/kibana/kibana:7.13.3
        #    container_name: kib
        #    ports:
        #      - 5601:5601
        #    environment:
        #      ELASTICSEARCH_URL: http://es:9200
        #      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
